# derived from https://github.com/rightsstatements/data-model/blob/master/rights-statements.ttl
terms:
  - id: http://rightsstatements.org/vocab/InC/1.0/
    term: In Copyright
    notable: false
    active: true
    scopeNote: |
      This Rights Statement can be used for an Item that is in copyright. Using
      this statement implies that Indiana University has determined
      that the Item is in copyright and either is the rights­holder, has
      obtained permission from the rights­holder(s) to make the Work available,
      or makes the Work available under an exception or limitation to copyright
      (including Fair Use) that entitles it to make the Work available.
  - id: http://rightsstatements.org/vocab/InC-RUU/1.0/
    term: In Copyright - Rights-holder(s) Unlocatable or Unidentifiable
    notable: true
    active: true
    scopeNote: |
      This Rights Statement is intended for use with an Item that has been
      identified as in copyright but for which no rights-holder(s) has been
      identified or located after some reasonable investigation. This Rights
      Statement should only be used if the data provider is reasonably sure
      that the work is in copyright. This Rights Statement is not intended for
      use by EU-based data providers who have identified works as Orphan Works
      in accordance with the EU Orphan Works Directive (they must use InC-OW-EU
      instead).
  - id: http://rightsstatements.org/vocab/InC-EDU/1.0/
    term: In Copyright - Educational Use Permitted
    notable: false
    active: true
    scopeNote: |
      This Rights Statement can be used only for copyrighted Items for which
      Indiana University is the rights-holder or has been explicitly
      authorized by the rights-holder(s) to allow third parties to use the Work
      for educational purposes without first obtaining permission.
  - id: http://rightsstatements.org/vocab/InC-NC/1.0/
    term: In Copyright - NonCommercial Use Permitted
    notable: false
    active: true
    scopeNote: |
      This Rights Statement can be used only for copyrighted Items for which
      Indiana University is the rights-holder or has been explicitly
      authorized by the rights-holder(s) to allow third parties to use the Work
      for non-commercial purposes without obtaining permission first.
  - id: http://rightsstatements.org/vocab/NoC-CR/1.0/
    term: No Copyright - Contractual Restrictions
    notable: false
    active: true
    scopeNote: |
      This Rights Statement can only be used for Items that are in the Public
      Domain but for which the data provider has entered into contractual
      agreement that requires it to take steps to restrict third party uses of
      the Item. In order for this Rights Statement to be conclusive, the data
      provider must provide a link to a page detailing the the contractual
      restrictions that apply to the use of the Item.
  - id: http://rightsstatements.org/vocab/NoC-OKLR/1.0/
    term: No Copyright - Other Known Legal Restrictions
    notable: false
    active: true
    scopeNote: |
      This Rights Statement should be used for Items that are in the public
      domain but that cannot be freely re-used as the consequence of known
      legal restrictions that prevent the data provider from allowing free
      re-use of the Work, such as cultural heritage or traditional cultural
      expression protections. In order for this Rights Statement to be
      conclusive, the data provider must provide a link to a page detailing
      the the legal restrictions that limit re-use of the Item.
  - id: http://rightsstatements.org/vocab/NoC-NC/1.0/
    term: No Copyright - Non-Commercial Use Only
    notable: false
    active: true
  - id: http://rightsstatements.org/vocab/NKC/1.0/
    term: No Known Copyright
    notable: false
    active: true
    scopeNote: |
      This Rights Statement should be used for Items for which the copyright
      status has not been determined conclusively, but for which the data
      provider has reasonable cause to believe that the work is not covered by
      copyright or related rights anymore. This Rights Statement should not be
      used for Orphan Works (which are assumed to be in-copyright) or for Works
      where the data provider has not undertaken an effort to ascertain the
      copyright status of the Work.
