development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/development" %>
test: &test
  adapter: solr
  url: <%= "http://localhost:#{ENV['TEST_JETTY_PORT'] || 8985}/solr/test" %>
production: &production
  adapter: solr
  url: <%= ENV['PLUM_SOLR_URL'] || "http://localhost:8983/solr/blacklight-core" %>
staging: 
  <<: *production
