development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8984/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8986/rest
  base_path: /test
production: &production
  user: <%= ENV["PMP_FEDORA_USER"] %>
  password: <%= ENV["PMP_FEDORA_PASS"] %>
  url: <%= ENV["PMP_FEDORA_URL"] %>
  base_path: <%= ENV["PMP_FEDORA_BASE"]	%>
staging:
  <<: *production
  base_path: /staging
