development:
  host: localhost
  port: 6379
test:
  host: localhost
  port: 6379
production: &production
  host: <%= ENV['PLUM_REDIS_URL'] || 'localhost' %>
  port: <%= ENV['PLUM_REDIS_PORT'] || '6379' %>
  namespace: 'plum'
staging:
  <<: *production
