development:
  host: <%= ENV['PMP_REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['PMP_REDIS_PORT'] || '6379' %>
  namespace: <%= ENV['PMP_REDIS_NS'] || 'pumpkin_dev' %>
test:
  host: localhost
  port: 6379
production: &production
  host: <%= ENV['PMP_REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['PMP_REDIS_PORT'] || '6379' %>
  namespace: <%= ENV['PMP_REDIS_NS'] || 'pumpkin_prod' %>
staging:
  <<: *production
