# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da515307c8c6e2e14f6d0814c2dfeadb1c5e910de318ac55e96d054e0a773ab2b3a9fbe74eca49d807129cdbed7b8b99624caa9b98b49eb4346f95b94ba2f073

test:
  secret_key_base: ad267625659653dedf905dd7d3de31d589808ea2fd27cb89247479b0cf700fa5e18bf0e49b0831c5d5bec7e26dca7d1e20dfbf7214174a455f91d53f9ba24e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  secret_key_base: <%= ENV["PMP_SECRET_KEY_BASE"] %>

staging:
  <<: *production
