---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - [permissions, 2]
  - [characterize, 2]
  - [audit, 2]
  - [id_based, 2]
  - [derivatives, 2]
  - [import_url, 2]
  - [ingest, 2]
  - [resolrize, 2]
  - [upload_set_update, 2]
